config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # can see all the list 'lists#index'
  # can see details of a given list and its name 'lists#show#
  # create a new list 'lists#create' 'lists#new'
  root to: 'lists#index'
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: [:destroy]
  # add a bookmark (movie/list pair) to an existing list  'bookmark#new' 'bookmark#create'
  # delete bookmark from a list 'bookmark#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, presence: true, uniqueness: { scope: :list }
  # this validates that if a movie is in the bookmark table, it can't have the same list.
  # another way of doing it - validates_uniqueness_of :movie, scope: :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true
  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    # @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name, label: 'List name'%>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<%= render 'components/banner', photo: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80' %>

<h1>My Lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

<%# <div class="card bg-dark text-white">
  <img class="card-img" src="..." alt="Card image">
  <div class="card-img-overlay">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text">Last updated 3 mins ago</p>
  </div>
</div> %>

<div class="row">
  <% @lists.each do |list| %>
    <div class="col-sm-4">
      <div class="card m-2" style = 'width: 18rem;'>
    <%= image_tag 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80', class:"card-img" %>
      <%# <img class="card-img" src="https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80" alt="Card image"> %>
        <div class="card-body card-img-overlay">
          <h5 class="card-title"><%= link_to list.name, list_path(list) %></h5>
          <%# <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> %>
          <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<p><%= link_to 'Add a new list', new_list_path(@list) %><p>

app/views/lists/new.html.erb
<%= render 'form', list: @list %>

<%= link_to 'Return to home page', lists_path %>

app/views/lists/show.html.erb
<%= render 'components/banner' , photo: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80' %>

<h1><%= @list.name %></h1>

<ul>
  <% @list.bookmarks.each do |bookmark| %>
    <ul>
      <li><strong>Movie title: <%= bookmark.movie.title%></strong></li>
      <li>Movie description: <%= bookmark.movie.overview%></li>
      <li>Movie rating: <%= bookmark.movie.rating%></li>
      <li>User comment: <%= bookmark.comment %></li>
      <li><%= link_to 'Delete this bookmark', bookmark_path(bookmark), method: :delete,
      data: { confirm: "Are you sure?" }  %></li>
    </ul>
    <% end %>
</ul>


<p><%= link_to 'Add a new bookmark', new_list_bookmark_path(@list) %></p>

<p><%= link_to 'Return to home page', lists_path %></p>